// MDUI 2.x 组件与全局样式统一在此注册，仅由浏览器入口 main.tsx 引入，
// 保证单元测试(jsdom)中自定义元素保持惰性、不触发 lit 运行时。
import 'mdui/mdui.css'
import '@fontsource/material-icons/400.css'

import 'mdui/components/avatar.js'
import 'mdui/components/button.js'
import 'mdui/components/button-icon.js'
import 'mdui/components/card.js'
import 'mdui/components/chip.js'
import 'mdui/components/circular-progress.js'
import 'mdui/components/dialog.js'
import 'mdui/components/divider.js'
import 'mdui/components/icon.js'
import 'mdui/components/layout.js'
import 'mdui/components/layout-main.js'
import 'mdui/components/linear-progress.js'
import 'mdui/components/list.js'
import 'mdui/components/list-item.js'
import 'mdui/components/menu.js'
import 'mdui/components/menu-item.js'
import 'mdui/components/navigation-bar.js'
import 'mdui/components/navigation-bar-item.js'
import 'mdui/components/navigation-drawer.js'
import 'mdui/components/navigation-rail.js'
import 'mdui/components/navigation-rail-item.js'
import 'mdui/components/segmented-button.js'
import 'mdui/components/segmented-button-group.js'
import 'mdui/components/select.js'
import 'mdui/components/snackbar.js'
import 'mdui/components/tab.js'
import 'mdui/components/tabs.js'
import 'mdui/components/text-field.js'
import 'mdui/components/tooltip.js'
import 'mdui/components/top-app-bar.js'
import 'mdui/components/top-app-bar-title.js'
